import Head from 'next/head'
import Container from '@/layout/Container'
import Col from '@/layout/Col'
import Grid from '@/layout/Grid'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='py-40'>
				<Container>
					<Grid mobileCols={2} tabletCols={12} desktopCols={12}>
						<Col>1</Col>
					</Grid>
				</Container>
			</main>
		</>
	)
}
