import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex w-full justify-between">
          <div className="bg-yellow-200 border-red-900 border-2 border-solid p-6 w-max cursor-pointer border-t-[20px] 768:p-12">
            Click me!!
          </div>
          <div className="bg-yellow-200 border-red-900 border-2 border-solid p-6 w-max cursor-pointer flex items-center 768:p-12 ">
            Submit!!
          </div>
          <div className="bg-regal-blue p-4 group w-max cursor-pointer hover:bg-black h-max">
            <span className="text-black  group-hover:text-white">
              Hello world
            </span>
          </div>
        </div>
      </main>
    </>
  );
}
