import Col from '@/components/styled-components/layout/Col'
import Grid from '@/components/styled-components/layout/Grid'
import Container from '@/components/ui/Container'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='py-80'>
				<Container>
					<h1>Test Title</h1>
					<Grid mobileCols={2} desktopCols={4} largeDesktopCols={6}>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>1</div>
						</Col>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>2</div>
						</Col>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>3</div>
						</Col>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>4</div>
						</Col>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>5</div>
						</Col>
						<Col>
							<div className='flex items-center justify-center p-8 text-white bg-primary'>6</div>
						</Col>
					</Grid>
				</Container>
			</main>
		</>
	)
}
